language: generic
matrix:
  include:
    - language: python
      python: 3.7
      install:
        pip3 install -r backend/requirements.txt
      before_script:
        - cd backend
      script: manage.py test
      cache: pip
    - addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - libstdc++6
            - fonts-droid-fallback
      before_script:
        - cd app
        - git clone https://github.com/flutter/flutter.git
        - ./flutter/bin/flutter doctor
      script:
        - ./flutter/bin/flutter test
      cache:
        directories:
          - $HOME/.pub-cache
