language: generic
jobs:
  include:
    - services:
        - docker
      install:
        - docker build backend/ -t bnctth/athena
        - docker build backend/nginx/ -t bnctth/athena_nginx
        - docker-compose up -d
      script: docker-compose exec web python manage.py test
    - addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - libstdc++6
            - fonts-droid-fallback
      before_script:
        - cd app
        - git clone https://github.com/flutter/flutter.git
        - ./flutter/bin/flutter doctor
      script:
        - ./flutter/bin/flutter test
      cache:
        directories:
          - $HOME/.pub-cache
