version: '3.7'

services:
  web:
    image: bnctth/athena
    command: bash -c "daphne backend.asgi:application -b 0.0.0.0 -p 8001 & gunicorn backend.wsgi:application --bind 0.0.0.0:8000"
    expose:
      - 8000
      - 8001
    env_file:
      - ./.env
    depends_on:
      - db
      - redis
    volumes:
      - static_volume:/home/athena/web/static
  db:
    image: postgres:12-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.db
  nginx:
    image: bnctth/athena_nginx
    ports:
      - 80:80
    depends_on:
      - web
    volumes:
      - static_volume:/home/athena/web/static
  redis:
    image: redis:5-alpine
    expose:
      - 6379

volumes:
  postgres_data:
  static_volume:

