version: '3.7'

services:
  web:
    build: backend
    command: bash -c "daphne backend.asgi:application -b 0.0.0.0 -p 8001 & gunicorn backend.wsgi:application --bind 0.0.0.0:8000"
    ports:
      - 8000:8000
      - 8001:8001
    env_file:
      - ./.env.dev
    depends_on:
      - db
      - redis
    volumes:
      - static_volume:/home/athena/web/static
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.db
  redis:
    image: redis:2.8
    expose: 
      - 6379
  nginx:
    build: backend/nginx
    ports:
      - 80:80
    depends_on:
      - web
    volumes:
      - static_volume:/home/athena/web/static

volumes:
  postgres_data:
  static_volume:

