# Generated by Django 3.0.3 on 2020-03-04 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yeelight_smartlamp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='yeelight',
            name='online',
            field=models.BooleanField(default=True),
        ),
    ]
